web:
    image: phalcon-nginx:latest
    ports:
        - "80:80"
    volumes:
        - ".:/app"
    links:
        - redis
        - mysql

redis:
    image: daocloud.io/daocloud/dao-redis:master-init
    ports:
        - "6379:6379"
    environment:
        REDIS_PASS: "**None**"

mysql:
    image: daocloud.io/daocloud/dao-mysql:5.6.25
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root123456
        MYSQL_DATABASE: lily
        MYSQL_USER: dataLily
        MYSQL_PASSWORD: hel123lo
